[profile.default]
solc_version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@dev/=lib/chainlink-brownie-contracts/contracts/src/v0.8/vrf/dev/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@solmate=lib/solmate/src"
]

# ffi = true

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 234

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
