[profile.default]
solc_version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@solmate=lib/solmate/src"
]

ffi = true

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
